name: 'workflow_run status'
description: 'Associate workflow_run status with the base commit of workflow_run triggered event'
author: 'haya14busa'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  requested_as_pending:
    description: 'handle requested action type as pending'
    default: true
    required: false
  matrix_name:
    description: 'current matrix name'
    default: ''
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: 'always()'
